2025-04-18 22:46:36,431 - ERROR - Token generation failed: 400 – {"error":"unauthorized_client"}
2025-04-18 23:26:03,693 - ERROR - ❌ Token refresh subprocess error: Traceback (most recent call last):
  File "/Users/Rahmel.moore/Documents/Code.Scripts/Project Saves/BOUNTEOUS/KIT/rtcdp_api_kit/config/ims.token_refresh.py", line 108, in <module>
    refresher = AEPTokenRefresher(credentials_path)
  File "/Users/Rahmel.moore/Documents/Code.Scripts/Project Saves/BOUNTEOUS/KIT/rtcdp_api_kit/config/ims.token_refresh.py", line 20, in __init__
    self.credentials = self.load_credentials()
                       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/Rahmel.moore/Documents/Code.Scripts/Project Saves/BOUNTEOUS/KIT/rtcdp_api_kit/config/ims.token_refresh.py", line 31, in load_credentials
    with open(self.credentials_file, "r") as file:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Rahmel.moore/Documents/Code.Scripts/Project Saves/BOUNTEOUS/KIT/rtcdp_api_kit/config/CREDS/cit_credentials.json'

2025-04-18 23:28:00,586 - ERROR - ❌ Token refresh subprocess error: Traceback (most recent call last):
  File "/Users/Rahmel.moore/Documents/Code.Scripts/Project Saves/BOUNTEOUS/KIT/rtcdp_api_kit/config/ims.token_refresh.py", line 108, in <module>
    refresher = AEPTokenRefresher(credentials_path)
  File "/Users/Rahmel.moore/Documents/Code.Scripts/Project Saves/BOUNTEOUS/KIT/rtcdp_api_kit/config/ims.token_refresh.py", line 20, in __init__
    self.credentials = self.load_credentials()
                       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/Rahmel.moore/Documents/Code.Scripts/Project Saves/BOUNTEOUS/KIT/rtcdp_api_kit/config/ims.token_refresh.py", line 31, in load_credentials
    with open(self.credentials_file, "r") as file:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Rahmel.moore/Documents/Code.Scripts/Project Saves/BOUNTEOUS/KIT/rtcdp_api_kit/config/config/cit-credentials.json'

2025-04-18 23:28:36,998 - INFO - ✔ Token refreshed using ims.token_refresh.py
2025-04-19 00:13:53,090 - ERROR - Token test request failed: HTTPSConnectionPool(host='platform.adobe.io', port=443): Max retries exceeded with url: /data/core/ups/config/mergePolicies (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)')))
2025-04-19 00:14:44,661 - INFO - ✔ Token refreshed using ims.token_refresh.py
